"""Initial migration

Revision ID: 146ce6b824d8
Revises: ff17d1b1c759
Create Date: 2024-12-25 16:15:31.572059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '146ce6b824d8'
down_revision = 'ff17d1b1c759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_name', sa.String(length=100), nullable=False),
    sa.Column('parent_category_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
